name: MoeItems
main: cn.whiteg.moeitems.MoeItems
version: 1.1
api-version: 1.13
author: MoeWhite
depend: [MMOCore, RPGArmour]
softdepend: [MoePacketAPI, Residence, dynmap]
commands:
  moeitems:
    description: The is moeitems Command
    aliases: ['mit']